services:
  - type: web
    name: NexusUB
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: PREFIX
        value: "."
      - key: LOG_GROUP
        sync: false
      - key: SUDO_USERS
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.0"
